// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/cloyop/tiniest/internal/templates/shared"

func PrivacyPolicy() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<body class=\"flex flex-col justify-center items-center w-full min-h-screen bg-bluer\"><a href=\"/\" class=\"absolute top-4 left-4\">⬅</a><div class=\"flex flex-col gap-4 w-10/12 md:w-8/12 font-medium shadow-b-outer2 bg-blue-dk py-4 px-2 text-aqua-light-3\"><section class=\"flex flex-col gap-2\"><h1 class=\"text-3xl text-white font-bold\">Privacy Policy</h1><p>Our URL shortening service is committed to protecting your privacy. This privacy policy explains what information we collect and how we use it\r</p></section><section><h2 class=\"text-2xl text-white font-semibold\">Information We Collect</h2><div class=\"h-2\"></div><p>We collect information about the URLs you shorten and the clicks on those links. This information includes the original URL, the shortened URL, the date and time of the click and the location from where the urls are visited.</p></section><section><h2 class=\"text-2xl text-white font-semibold\">How We Use Your Information</h2><p>We use the information we collect to provide and improve our service. We may also use it to troubleshoot problems and prevent abuse. We do not share your information with third parties, except as required by law.\r</p></section></div></body>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = shared.Page("Tiniest • Privacy Policy").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
