// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/cloyop/tiniest/internal/templates/shared"

func ProtectedRoute(key string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<body class=\"w-full h-screen overflow-hidden\"><a href=\"/\" class=\"text-2xl font-bold absolute top-4 left-4\"><span class=\"text-aqua-light\">TINI</span>EST\r</a><main class=\"w-full h-screen flex flex-col justify-center items-center\"><div class=\"flex flex-col justify-center items-center w-11/12 md:w-3/6 lg:w-2/6 rounded-lg shadow-b-outer2 p-2 bg-bluer\"><div class=\"p-4\"><h1 class=\"text-2xl font-medium text-aqua-light-2\">Protected Route</h1></div><form class=\"flex flex-col items-center gap-4 p-4 w-full\" hx-post=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("/" + key)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/protected-route.templ`, Line: 16, Col: 82}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-swap=\"none\"><label class=\"flex flex-col items-center gap-2 p-2 w-full text-xl font-medium\"><span>Password:</span> <input type=\"password\" name=\"password\" minlength=\"10\" maxlength=\"50\" autocomplete=\"off\" placeholder=\"Password\" class=\"bg-blue-dk text-xs border grow rounded-lg p-2 w-full md:w-4/6\"></label> <button class=\"w-36 h-8 bg-blue-dk border border-aqua-light-3 rounded-lg hover:border-2 font-bold text-aqua-light-2 \">Submit</button></form><div id=\"re\" class=\"w-full flex justify-center min-h-8 p-px\"></div></div></main><script defer src=\"static/js/pr.js\"></script></body>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = shared.Page("Tiniest").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
