// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/cloyop/tiniest/internal/templates/helpers"

func DashNewLinkForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"url-form\" hx-post=\"/pair/\" hx-target=\"#urls\" hx-swap=\"beforeend\" hx-indicator=\"#s-loader\" class=\"px-4 sm:px-0 flex flex-col gap-4 items-center w-full\"><label class=\"flex flex-col gap-2 p-2 w-full text-xl font-semibold\"><span class=\"flex w-full justify-between items-center \">Url: \r</span> <input type=\"text\" minlength=\"10\" autocomplete=\"off\" class=\"bg-bluer text-xs border border-aqua-light-3 grow rounded-lg p-2\" name=\"url\"></label> <label class=\"flex flex-col gap-2 p-2 w-full text-xl font-semibold\"><span class=\"flex justify-between items-baseline\">Title: <span class=\"text-xs text-aqua-light-3\">(optional)</span></span> <input type=\"text\" name=\"title\" autocomplete=\"off\" class=\"bg-bluer text-xs border border-aqua-light-3 grow rounded-lg p-2\"></label><div class=\"w-full\"><label class=\"flex gap-2 text-sm justify-between items-baseline w-full p-2 text-aqua-light-3\"><span class=\"\">Protect Your Route:</span> <input type=\"checkbox\" id=\"p-i\" autocomplete=\"off\" name=\"protect\" class=\"border rounded-lg p-2\"></label> <label class=\"hidden flex flex-col gap-2 p-2 w-full text-xl font-semibold\"><span class=\"\">Password:</span> <input type=\"password\" name=\"password\" autocomplete=\"off\" class=\"bg-bluer text-xs border border-aqua-light-3 grow rounded-lg p-2\"></label></div><div class=\"w-full flex justify-center gap-2\"><button type=\"submit\" class=\"w-36 h-8 bg-bluer border border-aqua-light-3 rounded-lg hover:border-2 font-bold text-aqua-light-2 \">Generate</button> <button type=\"button\" class=\"w-36 h-8 bg-bluer border border-aqua-light-3 rounded-lg hover:border-2 font-bold text-aqua-light-2 \" data-form=\"close\">Close</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = helpers.Loader("s-loader").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
